# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- 
  binary: azs
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - ppc64le
  ignore:
    - goos: darwin
      goarch: ppc64le
    - goos: windows
      goarch: ppc64le
archives:
  - 
    builds:
    - default
    replacements:
      darwin: macos
      linux: linux
      windows: win
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
        - goos: windows
          format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
